### ISSUE TITLE
Feat: query for the user's ERC20 tokens

### ISSUE THREAD

**Issue by Markus-55** [Viken-Blockchain-Solutions/TicketVault_stats#10]
## Issue:

- _We do not have access to the user's ERC20 tokens._ 

### Feature:

- _Query for all the user's ERC20 tokens information._

### Todo:

- [x] Display and query for the user's ERC20 tokens and balance.
- [x] Display native asset.
  - [x] Get the user's native asset balance.

### Resources:

- [Get native assets.](https://chainid.network/chains.json)
- [Get native asset balance.](https://docs.moralis.io/moralis-dapp/web3-api/account#getnativebalance)
- [Retrieve all user's ERC20 tokens and balances.](https://docs.moralis.io/moralis-dapp/web3-api/account#gettokenbalances)
